config/routes.rb
Rails.application.routes.draw do
  get 'ranking', to: 'score#index'
  put '/tasks/:id/conclude', to: 'tasks#conclude', as: :conclude_task

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  root 'home_controller#index'

  resources :users
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates :points, presence: true, numericality: { only_integer: true }
  validates :user_id, presence: true
  validates :task_id, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :status, presence: true, numericality: { only_integer: true }
  validates :difficulty, presence: true, numericality: { only_integer: true }
  validates :close_date, presence: true
  validates :close_limit_date, presence: true
  validates :user, presence: true

  after_save :check_conclusion

  private
  def check_conclusion
    if (self.status_changed?(from: 0, to: 1))
      score = Score.new
      score.task = self
      score.user = self.user
      score.points = set_pontuation
      score.save
    end
  end

  def set_pontuation
    score = 0
    if self.close_limit_date > Date.today
      score += 15
    elsif self.close_limit_date == Date.today
      score += 10
    elsif self.close_limit_date < Date.today
      score += 5
    end

    score = score * self.difficulty
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :scores

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/home_controller_controller.rb
class HomeControllerController < ApplicationController
  def index
    @tasks = Task.where(user: current_user).order(close_limit_date: :asc)
  end
end

app/controllers/score_controller.rb
class ScoreController < ApplicationController
  def index
    @ranking = User.joins(:scores)
                    .select('users.id, users.name, sum(scores.points) as points').group(:id)
                    .order('points DESC')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :conclude]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def conclude
    @task.update_attribute(:status, 1)
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :description, :status, :difficulty, :close_date, :close_limit_date, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :phone, :is_admin, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home_controller/index.html.erb
<h1>My Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Difficulty</th>
      <th>Close data</th>
      <th>Close limit date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.status %></td>
        <td><%= task.difficulty %></td>
        <td><%= task.close_date %></td>
        <td><%= task.close_limit_date %></td>
        <td><%= link_to 'Conclude', conclude_task_path(task) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoInHome</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <nav class="navbar navbar-full navbar-light bg-faded navbar-dark bg-inverse">
        <%= link_to "DoInHome", root_path, class: "navbar-brand" %>

        <ul class="nav navbar-nav">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link" do %>
                Início
            <% end -%>
          </li>

          <% if current_user.is_admin? %>
            <li class="nav-item">
              <%= link_to users_path, class: "nav-link" do %>
                <%= t(:user, scope: "activerecord.models").pluralize %>
              <% end -%>
            </li>
            <li class="nav-item">
              <%= link_to tasks_path, class: "nav-link" do %>
                <%= t(:task, scope: "activerecord.models").pluralize %>
              <% end -%>
            </li>
          <% end -%>
          <li class="nav-item">
            <%= link_to ranking_path, class: "nav-link" do %>
              <%= t(:ranking) %>
            <% end -%>
          </li>

          <li class="nav-item pull-right">
            <%= link_to destroy_user_session_path, class: "nav-link", method: :delete do %>
              Sair
            <% end -%>
          </li>
        </ul>
      </nav>
    <% end -%>

    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= render "shared/flash_messages" %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/score/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scores</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ranking.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.points %></td
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%
      if key == "alert"
        klass = "default"
      elsif key == "notice" || key == "success"
        klass = "info"
      elsif key == "timedout"
        klass = " hidden"
      elsif key == "custom_message"
        klass = "success"
      else
        klass = key
      end
    %>
    <%= content_tag(:div, class: "alert alert-#{klass} alert-dismissible fade in", role: "alert") do %>
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true"><i class="icon icn-logout"></i></span><span class="sr-only"><%= t(:close) %></span></button>
      <% if key == "custom_message" %>
        <i class="icon icn-faq"></i>
      <% end -%>
      <%= value %>
    <% end -%>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.number_field :status %>
  </div>

  <div class="field">
    <%= f.label :difficulty %>
    <%= f.number_field :difficulty %>
  </div>

  <div class="field">
    <%= f.label :close_date %>
    <%= f.date_select :close_date %>
  </div>

  <div class="field">
    <%= f.label :close_limit_date %>
    <%= f.date_select :close_limit_date %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th>Difficulty</th>
      <th>Close data</th>
      <th>Close limit date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= task.difficulty %></td>
        <td><%= task.close_date %></td>
        <td><%= task.close_limit_date %></td>
        <td><%= task.user.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Difficulty:</strong>
  <%= @task.difficulty %>
</p>

<p>
  <strong>Close data:</strong>
  <%= @task.close_date %>
</p>

<p>
  <strong>Close limit date:</strong>
  <%= @task.close_limit_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :is_admin %>
    <%= f.check_box :is_admin %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Is admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.is_admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Is admin:</strong>
  <%= @user.is_admin %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Password confirmation:</strong>
  <%= @user.password_confirmation %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>